### ISSUE TITLE
3DObject on 2D layer rendering artifacts

### ISSUE THREAD

**Issue by F3der1co** [MikalDev/3dobject#23]
Left side: 3DObject on a layer set to 2D Rendering Mode
Right side: for control, on 3D Rendering Mode

https://github.com/user-attachments/assets/56ce9f6e-5446-4649-b2a4-142541f71f8d

My specific use case for this is a skin unlock/selector dialog that is displayed on top of the game.
Other cases could be inventories etc. with 3d objects.

**Comment by MikalDev** [comment]
As discussed on Discord, 3D Object will only render correctly on 3D layers (which include a depth buffer, 2D layers do not.)
